name: Auto-post to Bear Blog

on:
  push:
    paths:
      - journal.txt

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Post to Bear Blog
        run: node post.js
        env:
          BEAR_EMAIL: ${{ secrets.BEAR_EMAIL }}
          BEAR_PASSWORD: ${{ secrets.BEAR_PASSWORD }}
          BEAR_URL: ${{ secrets.BEAR_URL }}
